apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
      - name: pacman
        image:  416338226474.dkr.ecr.us-east-2.amazonaws.com/myapps/pacman:7a2c186984efc582ba31da5612d7c01a2774edf9
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: pacman-config
